### PR TITLE
Boot log #84

### LINKED ISSUE #84: Make use of device log on server
E.g. startup, branch, reboot

### PR DESCRIPTION
**Pull request by bplimley**
Closes #84, #60
Device sends a log message to server when it boots.

This also sets the network LED based on the success of the log transmission.

### CODE REVIEW

**Comment by bplimley** [comment]
If we want to test the device update issues, we might wait until tomorrow to merge this.

**Comment by bplimley** [comment]
Ah, actually there's an error when `dosenet.sh` runs `manager.py` because the working directory is not in the git repo...

**Comment by bplimley** [comment]
Okay, fixed. Tested with `git-pull-reboot.sh` and the pi comes on with a working manager in `screen`.

**Comment by alihanks** [comment]
I agree that waiting until tomorrow would be a nice change to test updating.

**Review by alihanks — APPROVED** [review]

**Pull request merged**
