### PR TITLE
Changes the D3S backlog file to csv format and Editing how D3S handles LEDS

### PR DESCRIPTION
**Pull request by tybtab**
Replaced the old backlog_d3s with a csv format. 

Also as a parser, ast.literal_eval is great, but it breaks down if what it parses is too large. So it only will parse now a little at a time.

Don't merge this yet because I'm going to try it on a test device this weekend.

### CODE REVIEW

**Review by bplimley — APPROVED** [review]
Looks fine to me. As long as you've tested it carefully and it works.

**Comment by tybtab** [comment]
Just making sure the format works for Python 2.7.

**Comment by tybtab** [comment]
Should I also make it so only the silicon sensor controls the LEDs? Having both seems redundant....

**Comment by bplimley** [comment]
I don't remember what the D3S does with the LEDs, but just one should control the LEDs and the silicon sensor is simpler to represent with lights.

Unless we used the blue LED to indicate D3S status... like red = PocketGeiger status, blue = D3S status, green = network... potentially confusing though with a solid blue light.

**Comment by bplimley** [comment]
@alihanks ?

**Comment by tybtab** [comment]
So far its working good. I was able to get it to transfer from backlog to a queue of length 25 and it supposedly sent it all to server

**Comment by tybtab** [comment]
Worked fine for a length of 16

**Comment by tybtab** [comment]
Ok going to focus on running the 2 devices run together now. D3S buffer seems to be working fine

**Comment by bplimley** [comment]
There's a conflict on `data_handler_d3s.py`, can you merge master?

**Comment by tybtab** [comment]
Conflict resolved.

**Comment by bplimley** [comment]
@alihanks may want to use the red LED as a status indicator on the D3S, for you guys to discuss later.

**Pull request merged**
